/**
 * AYUSHI REAL ESTATE - SAMPLE DATABASE DATASET
 * Enhanced with:
 * - 5 Developers
 * - 6 Off-Plan Projects
 * - 16 Ready Properties across Dubai Marina, Downtown, Palm Jumeirah, Business Bay, Dubai Hills, and JVC
 * - 3 Staff Logins (Admin: Ayushi Kapoor, Agents: Tariq Al-Hashimi, Elena Rostova)
 * - 40 Buyer Leads with Scores (0-100), HOT/WARM/COLD, Stages, Source Forms, and Activity Timestamps
 * - 10 Viewings
 * - 5 Completed Sales
 * - Notes
 */

export const developers = [
  {
    id: 1,
    name: "Solana Prime Developments",
    tagline: "Ultra-luxury waterfront sanctuaries and private island estates",
    description: "Pioneering private peninsula villas and branded coastal architectural monuments with bespoke master-craftsmanship.",
    headquarters: "DIFC Gate Precinct, Dubai",
    established_year: 2012,
    delivered_projects: 14
  },
  {
    id: 2,
    name: "Vanguard Horizons Group",
    tagline: "Futuristic architectural towers shaping the new Dubai skyline",
    description: "Specializing in high-altitude residences, cantilevered sky villas, and vertical botanical environments.",
    headquarters: "Downtown Boulevard, Dubai",
    established_year: 2015,
    delivered_projects: 11
  },
  {
    id: 3,
    name: "Aura Luxury Properties",
    tagline: "Golf sanctuary mansions and sustainable biophilic living",
    description: "World-class private residential enclaves designed in harmony with manicured fairways and natural desert geology.",
    headquarters: "Dubai Hills Business Park",
    established_year: 2014,
    delivered_projects: 9
  },
  {
    id: 4,
    name: "Elysian Bay Developments",
    tagline: "Bespoke beachfront residences and boutique private resorts",
    description: "Curated shoreline addresses offering private marina docks, stepped glass terraces, and Michelin-partnered amenities.",
    headquarters: "Jumeirah Coast, Dubai",
    established_year: 2017,
    delivered_projects: 7
  },
  {
    id: 5,
    name: "Zenith Living Real Estate",
    tagline: "Minimalist Italian architecture in Dubai's premier postal codes",
    description: "Timeless contemporary residences featuring travertine stone, floor-to-ceiling glass, and quiet luxury interiors.",
    headquarters: "City Walk, Dubai",
    established_year: 2016,
    delivered_projects: 12
  }
];

export const offplanProjects = [
  {
    id: 1,
    developer_id: 2,
    developer_name: "Vanguard Horizons Group",
    name: "Lumina Sky Tower",
    slug: "lumina-sky-tower",
    community: "Business Bay",
    starting_price_aed: 3850000,
    handover_date: "Q4 2027",
    payment_plan: "60/40 Construction Linked",
    down_payment_pct: 10,
    construction_pct: 50,
    handover_pct: 40,
    property_types: "1, 2, 3 & 4 Bed Sky Suites, Penthouses",
    image_url: "assets/images/lumina-tower-offplan.jpg",
    description: "A 68-storey sculptural tower rising above the Dubai Canal, featuring cantilevered plunge pools on each private terrace and multi-tier botanical gardens.",
    projected_roi: "9.4%",
    amenities: [
      "Balcony Plunge Pools",
      "Cantilevered Sky Lounge",
      "Multi-Tier Botanical Gardens",
      "Residents' Cigar Lounge",
      "Hydrotherapy Wellness Suite",
      "0% Broker Commission",
      "10-Year Golden Visa Eligible"
    ]
  },
  {
    id: 2,
    developer_id: 4,
    developer_name: "Elysian Bay Developments",
    name: "Crest Beachfront Residences",
    slug: "crest-beachfront-residences",
    community: "Jumeirah Coastline",
    starting_price_aed: 5900000,
    handover_date: "Q2 2028",
    payment_plan: "70/30 (30% on Handover)",
    down_payment_pct: 20,
    construction_pct: 50,
    handover_pct: 30,
    property_types: "2 to 5 Bed Waterfront Mansions",
    image_url: "assets/images/crest-beachfront-tower.jpg",
    description: "Stepped architectural terraces overlooking the open sea with private glass infinity pools and direct access to an exclusive beach club promenade.",
    projected_roi: "8.8%",
    amenities: [
      "Private Beach Club Membership",
      "Terrace Glass Infinity Pools",
      "Superyacht Mooring Services",
      "Private Chauffeur Valet",
      "Sunset Horizon Views",
      "Golden Visa Eligible"
    ]
  },
  {
    id: 3,
    developer_id: 1,
    developer_name: "Solana Prime Developments",
    name: "Solana Water Villas",
    slug: "solana-water-villas",
    community: "Palm Jumeirah",
    starting_price_aed: 18200000,
    handover_date: "Q1 2028",
    payment_plan: "50/50 Handover Linked",
    down_payment_pct: 20,
    construction_pct: 30,
    handover_pct: 50,
    property_types: "4 & 5 Bed Overwater Villas",
    image_url: "assets/images/palm-waterfront-villa.jpg",
    description: "Limited collection of 28 overwater and beachfront villas on the Palm crescent, with private boat slips, underwater dining lounges, and bespoke Molteni&C kitchens.",
    projected_roi: "8.2%",
    amenities: [
      "Private Boat Berth",
      "Underwater Observation Lounge",
      "Rooftop Stargazing Deck",
      "Private Infinity Edge Pool",
      "24/7 Island Butler Concierge"
    ]
  },
  {
    id: 4,
    developer_id: 5,
    developer_name: "Zenith Living Real Estate",
    name: "Zenith Skyline Duplexes",
    slug: "zenith-skyline-duplexes",
    community: "Downtown",
    starting_price_aed: 6400000,
    handover_date: "Q3 2027",
    payment_plan: "60/40 Construction Linked",
    down_payment_pct: 15,
    construction_pct: 45,
    handover_pct: 40,
    property_types: "2, 3 & 4 Bed Double-Height Duplexes",
    image_url: "assets/images/downtown-penthouse.jpg",
    description: "Ultra-sleek glass duplexes with 6-meter ceiling voids framing direct views of the Burj Khalifa and Opera district.",
    projected_roi: "9.1%",
    amenities: [
      "Burj Khalifa Skyline Panorama",
      "Double Height Living Rooms",
      "Private Elevator Access",
      "Wine Cellar & Tasting Room",
      "Direct Boulevard Connection"
    ]
  },
  {
    id: 5,
    developer_id: 3,
    developer_name: "Aura Luxury Properties",
    name: "Aura Serenity Mansions",
    slug: "aura-serenity-mansions",
    community: "Dubai Hills",
    starting_price_aed: 24500000,
    handover_date: "Q4 2027",
    payment_plan: "70/30 Milestone Linked",
    down_payment_pct: 20,
    construction_pct: 50,
    handover_pct: 30,
    property_types: "6 & 7 Bed Fairway Mansions",
    image_url: "assets/images/elysian-mansion.jpg",
    description: "Surrounded by championship greens, each mansion features basalt water walls, subterranean 8-car galleries, and private wellness spas.",
    projected_roi: "7.9%",
    amenities: [
      "Championship Golf Views",
      "Subterranean Car Gallery",
      "Private Spa & Hammam",
      "Zen Meditation Courtyard",
      "Smart Biometric Security"
    ]
  },
  {
    id: 6,
    developer_id: 2,
    developer_name: "Vanguard Horizons Group",
    name: "Vanguard Central Horizon",
    slug: "vanguard-central-horizon",
    community: "JVC",
    starting_price_aed: 1450000,
    handover_date: "Q1 2027",
    payment_plan: "60/40 Post-Handover Available",
    down_payment_pct: 10,
    construction_pct: 50,
    handover_pct: 40,
    property_types: "Studio, 1 & 2 Bed Smart Apartments",
    image_url: "assets/images/marina-residence.jpg",
    description: "High-yield investment opportunity in JVC featuring smart automation, co-working lounges, rooftop pool club, and strong rental tenancy appeal.",
    projected_roi: "10.5%",
    amenities: [
      "High Rental Yield Focus",
      "Rooftop Pool & Sunset Bar",
      "Executive Co-Working Hub",
      "EV Charging Stations",
      "Fully Furnished Designer Options"
    ]
  }
];

export const readyProperties = [
  // 1. Palm Jumeirah
  {
    id: 1,
    title: "The Palm Reserve Villa",
    slug: "the-palm-reserve-villa",
    reference_no: "AYU-PJ-001",
    property_type: "Villa",
    status: "Ready",
    community: "Palm Jumeirah",
    sub_community: "Frond N",
    price_aed: 48500000,
    bedrooms: 6,
    bathrooms: 8,
    built_up_area_sqft: 11200,
    plot_size_sqft: 15800,
    parking_spaces: 6,
    view_type: "Direct Arabian Gulf & Marina Skyline",
    service_charges_per_sqft: 16.5,
    image_url: "assets/images/palm-waterfront-villa.jpg",
    description: "An architectural masterpiece poised on one of Palm Jumeirah's most private fronds. Seamless indoor-outdoor living, travertine terraces, 22m infinity pool spilling into the sea, private yacht mooring, and bespoke Italian interior joinery.",
    amenities: ["Private Beach Access", "Infinity Edge Pool", "Private Yacht Mooring", "Smart Home Automation", "Sub-Zero & Wolf Appliances", "Staff Quarters", "Wellness Spa"],
    is_featured: true
  },
  {
    id: 2,
    title: "Palm Crescent Ocean Estate",
    slug: "palm-crescent-ocean-estate",
    reference_no: "AYU-PJ-002",
    property_type: "Villa",
    status: "Ready",
    community: "Palm Jumeirah",
    sub_community: "East Crescent",
    price_aed: 72000000,
    bedrooms: 7,
    bathrooms: 9,
    built_up_area_sqft: 15400,
    plot_size_sqft: 21000,
    parking_spaces: 8,
    view_type: "Open Sea & Royal Atlantis Panorama",
    service_charges_per_sqft: 18.0,
    image_url: "assets/images/palm-waterfront-villa.jpg",
    description: "Palatial residence featuring private white-sand beach frontage, Olympic lap pool, private glass elevator, screening room, and dual chef kitchens.",
    amenities: ["Private 80m Beachfront", "Glass Elevator", "12-Seat Cinema Room", "Wine Vault", "Dual Chef Kitchens", "Infinity Pool", "Private Security Post"],
    is_featured: false
  },
  {
    id: 3,
    title: "Golden Mile Sky Terrace Residence",
    slug: "golden-mile-sky-terrace",
    reference_no: "AYU-PJ-003",
    property_type: "Penthouse",
    status: "Ready",
    community: "Palm Jumeirah",
    sub_community: "Trunk",
    price_aed: 11500000,
    bedrooms: 3,
    bathrooms: 4,
    built_up_area_sqft: 3800,
    plot_size_sqft: 0,
    parking_spaces: 3,
    view_type: "Palm Park & Marina Skyline",
    service_charges_per_sqft: 21.0,
    image_url: "assets/images/marina-residence.jpg",
    description: "Expansive penthouse with an immense landscaped outdoor terrace, bespoke Poliform wardrobes, and direct pedestrian access to the Palm Jumeirah park promenade.",
    amenities: ["Huge Wrap-Around Terrace", "Park View", "Direct Boardwalk Access", "Valet Parking", "Concierge Service"],
    is_featured: false
  },

  // 2. Downtown Dubai
  {
    id: 4,
    title: "The Grand Horizon Penthouse",
    slug: "the-grand-horizon-penthouse",
    reference_no: "AYU-DT-001",
    property_type: "Penthouse",
    status: "Ready",
    community: "Downtown",
    sub_community: "Burj Crown District",
    price_aed: 34000000,
    bedrooms: 5,
    bathrooms: 6,
    built_up_area_sqft: 8900,
    plot_size_sqft: 0,
    parking_spaces: 4,
    view_type: "Unobstructed Burj Khalifa & Fountain",
    service_charges_per_sqft: 28.5,
    image_url: "assets/images/downtown-penthouse.jpg",
    description: "Perched high above Downtown Dubai, this double-height sky duplex commands panoramic views of the Burj Khalifa and the fountains. Custom marble finishes, soaring 7m glass walls, private wine cellar, and dedicated elevator.",
    amenities: ["Burj Khalifa Centerpiece View", "Private Dedicated Elevator", "Double-Height Salon", "Climate-Controlled Wine Room", "Private Heated Plunge Pool", "24/7 Valet"],
    is_featured: true
  },
  {
    id: 5,
    title: "Boulevard Opera View Suite",
    slug: "boulevard-opera-view-suite",
    reference_no: "AYU-DT-002",
    property_type: "Apartment",
    status: "Ready",
    community: "Downtown",
    sub_community: "Opera District",
    price_aed: 6200000,
    bedrooms: 2,
    bathrooms: 3,
    built_up_area_sqft: 1850,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Dubai Opera & Boulevard",
    service_charges_per_sqft: 25.0,
    image_url: "assets/images/downtown-penthouse.jpg",
    description: "Refined corner apartment directly adjacent to the Dubai Opera House. Features floor-to-ceiling glass, Italian marble bathrooms, and a deep sunset loggia.",
    amenities: ["Opera District Address", "Sunset Terrace", "Infinity Pool Overlooking Burj", "Gymnasium", "24/7 Security"],
    is_featured: false
  },
  {
    id: 6,
    title: "Old Town Island Courtyard Residence",
    slug: "old-town-island-courtyard",
    reference_no: "AYU-DT-003",
    property_type: "Apartment",
    status: "Ready",
    community: "Downtown",
    sub_community: "Old Town Island",
    price_aed: 4800000,
    bedrooms: 2,
    bathrooms: 2,
    built_up_area_sqft: 1600,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Lush Arabic Courtyard & Fountains",
    service_charges_per_sqft: 22.0,
    image_url: "assets/images/luxury-concierge.jpg",
    description: "Charming traditional Arabic low-rise architecture combined with high-end modern interiors. Private garden patio, high beamed ceilings, and pedestrian serenity in the heart of Downtown.",
    amenities: ["Private Courtyard Garden", "Low-Rise Living", "Steps to Souk Al Bahar", "Swimming Pool", "Heritage Architecture"],
    is_featured: false
  },

  // 3. Dubai Hills
  {
    id: 7,
    title: "Elysian Estate Golf Mansion",
    slug: "elysian-estate-golf-mansion",
    reference_no: "AYU-DH-001",
    property_type: "Villa",
    status: "Ready",
    community: "Dubai Hills",
    sub_community: "Hills Grove",
    price_aed: 58000000,
    bedrooms: 7,
    bathrooms: 9,
    built_up_area_sqft: 14500,
    plot_size_sqft: 22000,
    parking_spaces: 8,
    view_type: "18-Hole Championship Fairways & Skyline",
    service_charges_per_sqft: 9.5,
    image_url: "assets/images/elysian-mansion.jpg",
    description: "An ultra-rare modern sanctuary within Dubai Hills. Floating travertine walkways over water reflection ponds lead into an architectural triumph of glass and cedar wood. 18m lap pool and sunken conversation fire pits.",
    amenities: ["Championship Golf Frontline", "Floating Travertine Entry", "18m Lap Pool", "Sunken Fire Pit Lounge", "Basement 8-Car Gallery", "Private Cinema", "Smart Home Automation"],
    is_featured: true
  },
  {
    id: 8,
    title: "Hills Parkside Modern Villa",
    slug: "hills-parkside-modern-villa",
    reference_no: "AYU-DH-002",
    property_type: "Villa",
    status: "Ready",
    community: "Dubai Hills",
    sub_community: "Fairway Vistas",
    price_aed: 18500000,
    bedrooms: 5,
    bathrooms: 6,
    built_up_area_sqft: 6800,
    plot_size_sqft: 9200,
    parking_spaces: 4,
    view_type: "Park & Skyline",
    service_charges_per_sqft: 10.0,
    image_url: "assets/images/elysian-mansion.jpg",
    description: "Contemporary family villa with double-volume entry, floor-to-ceiling glass, private landscaped garden with overflow pool, and direct access to Dubai Hills central park.",
    amenities: ["Private Pool", "Landscaped Garden", "Maid's & Driver's Rooms", "Gourmet Kitchen", "Near King's College Hospital"],
    is_featured: false
  },
  {
    id: 9,
    title: "Club Villas Sunset Residence",
    slug: "club-villas-sunset-residence",
    reference_no: "AYU-DH-003",
    property_type: "Villa",
    status: "Ready",
    community: "Dubai Hills",
    sub_community: "Club Villas",
    price_aed: 9800000,
    bedrooms: 4,
    bathrooms: 5,
    built_up_area_sqft: 4100,
    plot_size_sqft: 4900,
    parking_spaces: 2,
    view_type: "Golf Clubhouse & Sunset",
    service_charges_per_sqft: 11.2,
    image_url: "assets/images/elysian-mansion.jpg",
    description: "Elegant modern villa with rooftop entertaining terrace commanding 360-degree views over the golf clubhouse and Dubai skyline.",
    amenities: ["Rooftop Sky Lounge", "Golf View", "Private Garden", "Gated Security", "Close to Clubhouse"],
    is_featured: false
  },

  // 4. Dubai Marina
  {
    id: 10,
    title: "Marina Promontory Penthouse",
    slug: "marina-promontory-penthouse",
    reference_no: "AYU-DM-001",
    property_type: "Penthouse",
    status: "Ready",
    community: "Dubai Marina",
    sub_community: "Marina Promenade",
    price_aed: 14200000,
    bedrooms: 4,
    bathrooms: 5,
    built_up_area_sqft: 4200,
    plot_size_sqft: 0,
    parking_spaces: 3,
    view_type: "Superyacht Marina & Ain Dubai",
    service_charges_per_sqft: 22.0,
    image_url: "assets/images/marina-residence.jpg",
    description: "Spectacular corner residence commanding wrap-around sunset views over Dubai Marina's superyacht basin. Features bespoke Poliform kitchen cabinetry and oversized entertaining loggias.",
    amenities: ["Superyacht Marina Basin Views", "Wrap-Around Sunset Terrace", "Bespoke Poliform Kitchen", "Private Marina Berth Rights", "Residents' Infinity Pool"],
    is_featured: true
  },
  {
    id: 11,
    title: "Bluewaters Waterfront Haven",
    slug: "bluewaters-waterfront-haven",
    reference_no: "AYU-DM-002",
    property_type: "Apartment",
    status: "Ready",
    community: "Dubai Marina",
    sub_community: "Bluewaters Island",
    price_aed: 8900000,
    bedrooms: 3,
    bathrooms: 4,
    built_up_area_sqft: 2750,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Sea & Ain Dubai Wheel",
    service_charges_per_sqft: 26.0,
    image_url: "assets/images/marina-residence.jpg",
    description: "Island living moments from the mainland. Scandinavian minimalist interiors, expansive sea-facing terrace, and steps from world-class dining promenades.",
    amenities: ["Direct Ain Dubai Views", "Beach Access", "Infinity Edge Pools", "Retail & Fine Dining at Doorstep", "24/7 Concierge"],
    is_featured: false
  },
  {
    id: 12,
    title: "Marina Gate Panoramic Suite",
    slug: "marina-gate-panoramic-suite",
    reference_no: "AYU-DM-003",
    property_type: "Apartment",
    status: "Ready",
    community: "Dubai Marina",
    sub_community: "Marina Gate",
    price_aed: 4750000,
    bedrooms: 2,
    bathrooms: 2,
    built_up_area_sqft: 1520,
    plot_size_sqft: 0,
    parking_spaces: 1,
    view_type: "Full Marina Waterway",
    service_charges_per_sqft: 24.0,
    image_url: "assets/images/marina-residence.jpg",
    description: "High-floor turnkey residence overlooking the main yacht channel with floor-to-ceiling glass and state-of-the-art residential wellness center.",
    amenities: ["Full Water View", "Infinity Pool", "Dual-Level Gym", "Tennis & Paddle Court", "24/7 Security"],
    is_featured: false
  },

  // 5. Business Bay
  {
    id: 13,
    title: "Canal Promontory Sky Residence",
    slug: "canal-promontory-sky-residence",
    reference_no: "AYU-BB-001",
    property_type: "Apartment",
    status: "Ready",
    community: "Business Bay",
    sub_community: "Marasi Bay",
    price_aed: 3400000,
    bedrooms: 2,
    bathrooms: 3,
    built_up_area_sqft: 1450,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Dubai Water Canal & Downtown Skyline",
    service_charges_per_sqft: 20.0,
    image_url: "assets/images/lumina-tower-offplan.jpg",
    description: "Direct waterfront apartment on the Dubai Water Canal promenade. Italian marble finishes, automated acoustic blinds, and expansive sunset balcony.",
    amenities: ["Canal Promenade Access", "Yacht Marina Berths", "Sky Pool", "Smart Keyless Entry", "Meeting Rooms"],
    is_featured: false
  },
  {
    id: 14,
    title: "Executive Bay Corner Duplex",
    slug: "executive-bay-corner-duplex",
    reference_no: "AYU-BB-002",
    property_type: "Penthouse",
    status: "Ready",
    community: "Business Bay",
    sub_community: "Executive Bay",
    price_aed: 5200000,
    bedrooms: 3,
    bathrooms: 4,
    built_up_area_sqft: 2600,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Burj Khalifa & Canal Crossing",
    service_charges_per_sqft: 21.5,
    image_url: "assets/images/downtown-penthouse.jpg",
    description: "Dramatic corner duplex with double-height glass framing the city lights. Features internal floating glass staircase and dual master suites.",
    amenities: ["Duplex Layout", "Burj Khalifa Panorama", "Dual Master Suites", "Concierge Service", "Valet Parking"],
    is_featured: false
  },

  // 6. JVC (Jumeirah Village Circle)
  {
    id: 15,
    title: "District 12 Signature Townhouse",
    slug: "district-12-signature-townhouse",
    reference_no: "AYU-JVC-001",
    property_type: "Townhouse",
    status: "Ready",
    community: "JVC",
    sub_community: "District 12",
    price_aed: 2850000,
    bedrooms: 4,
    bathrooms: 5,
    built_up_area_sqft: 3300,
    plot_size_sqft: 2600,
    parking_spaces: 2,
    view_type: "Community Park & Garden",
    service_charges_per_sqft: 4.5,
    image_url: "assets/images/elysian-mansion.jpg",
    description: "Modern 4-bedroom townhouse with private plunge pool, private elevator provision, maid's room, and rooftop BBQ lounge. Exceptional family living or rental yield.",
    amenities: ["Private Plunge Pool", "Rooftop BBQ Lounge", "Park-Facing", "Maid's Room", "Low Service Charges"],
    is_featured: false
  },
  {
    id: 16,
    title: "Circle Central Designer Penthouse",
    slug: "circle-central-designer-penthouse",
    reference_no: "AYU-JVC-002",
    property_type: "Penthouse",
    status: "Ready",
    community: "JVC",
    sub_community: "Circle Mall District",
    price_aed: 2150000,
    bedrooms: 3,
    bathrooms: 3,
    built_up_area_sqft: 2200,
    plot_size_sqft: 0,
    parking_spaces: 2,
    view_type: "Community Skyline & Sunset",
    service_charges_per_sqft: 12.0,
    image_url: "assets/images/marina-residence.jpg",
    description: "Turnkey top-floor penthouse with huge terrace and integrated jacuzzi. Fully furnished with contemporary Scandinavian furniture and smart home lighting.",
    amenities: ["Terrace Jacuzzi", "Fully Furnished", "High Rental Yield", "Close to Circle Mall", "Gym & Pool"],
    is_featured: false
  }
];

export const staffLogins = [
  {
    id: 1,
    name: "Ayushi Kapoor",
    email: "ayushi@ayushirealestate.ae",
    password: "admin123",
    role: "Managing Director & Founder",
    is_admin: true,
    phone: "+971 4 820 9001",
    avatar_initials: "AK",
    rera_license: "RERA-42801",
    monthly_target_aed: 80000000
  },
  {
    id: 2,
    name: "Tariq Al-Hashimi",
    email: "tariq@ayushirealestate.ae",
    password: "tariq123",
    role: "Senior VP, Private Client Advisory",
    is_admin: false,
    phone: "+971 50 882 1100",
    avatar_initials: "TA",
    rera_license: "RERA-51920",
    monthly_target_aed: 50000000
  },
  {
    id: 3,
    name: "Elena Rostova",
    email: "elena@ayushirealestate.ae",
    password: "elena123",
    role: "Director of Off-Plan Acquisitions",
    is_admin: false,
    phone: "+971 52 449 8830",
    avatar_initials: "ER",
    rera_license: "RERA-64312",
    monthly_target_aed: 40000000
  }
];

// Helper to calculate days ago ISO string
function daysAgo(days) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const sampleLeads = [
  // HOT Leads (Score >= 70)
  {
    id: 1,
    full_name: "Sir James Thornton",
    email: "j.thornton@mayfair-invest.co.uk",
    phone: "+44 7911 123456",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (The Palm Reserve Villa)",
    preferred_community: "Palm Jumeirah",
    property_id: 1,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 48500000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 95,
    temperature: "HOT",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Interested in private beach villa, arriving via private flight next Tuesday. Cash settlement ready.",
    last_activity_at: daysAgo(0) // Today
  },
  {
    id: 2,
    full_name: "Sheikh Mansoor Al-Qasimi",
    email: "m.alqasimi@gulfcapital.ae",
    phone: "+971 50 999 8811",
    lead_type: "Register Interest",
    source_form: "Home Hero Register",
    preferred_community: "Dubai Hills",
    property_id: 7,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 58000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 95,
    temperature: "HOT",
    stage: "Offer",
    assigned_agent_id: 1,
    message: "Looking for prime golf frontline mansion for immediate cash settlement. Proof of funds verified.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 3,
    full_name: "Sophia Van Der Bilt",
    email: "sophia@vanderbilt-holdings.nl",
    phone: "+31 20 555 0192",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (Downtown Penthouse)",
    preferred_community: "Downtown",
    property_id: 4,
    budget_bracket_aed: "AED 25M - AED 50M",
    deal_value_aed: 34000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 90,
    temperature: "HOT",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Requesting private viewing of Grand Horizon Duplex with legal counsel. Funds allocated.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 4,
    full_name: "Natalia Vodianova",
    email: "natalia@monaco-family.mc",
    phone: "+377 98 98 00 11",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Palm Crescent Ocean Estate)",
    preferred_community: "Palm Jumeirah",
    property_id: 2,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 72000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 95,
    temperature: "HOT",
    stage: "Offer",
    assigned_agent_id: 1,
    message: "High privacy VIP viewing of Ocean Estate with chauffeur protocol.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 5,
    full_name: "Hassan Al-Majid",
    email: "almajid@doha-inv.qa",
    phone: "+974 5551 2345",
    lead_type: "Register Interest",
    source_form: "VIP Concierge Modal",
    preferred_community: "Dubai Hills",
    property_id: 7,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 58000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 90,
    temperature: "HOT",
    stage: "Won",
    assigned_agent_id: 1,
    message: "Mansion acquisition for personal family residency successfully agreed.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 6,
    full_name: "Sebastian Vance",
    email: "svance@vance-am.com",
    phone: "+1 212 555 0199",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (Downtown Penthouse)",
    preferred_community: "Downtown",
    property_id: 4,
    budget_bracket_aed: "AED 25M - AED 50M",
    deal_value_aed: 34000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 85,
    temperature: "HOT",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Proof of funds ready, looking to finalize before end of month.",
    last_activity_at: daysAgo(0)
  },
  {
    id: 7,
    full_name: "Zaid Al-Bahar",
    email: "zaid@kuwait-marine.kw",
    phone: "+965 9912 3456",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (Palm Reserve Villa)",
    preferred_community: "Palm Jumeirah",
    property_id: 1,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 48500000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 90,
    temperature: "HOT",
    stage: "Viewing",
    assigned_agent_id: 1,
    message: "Berthing capacity check for 120ft yacht. Immediate cash transaction.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 8,
    full_name: "Victoria Romanova",
    email: "v.romanova@zurich-private.ch",
    phone: "+41 44 220 9011",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Palm Crescent)",
    preferred_community: "Palm Jumeirah",
    property_id: 2,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 72000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 95,
    temperature: "HOT",
    stage: "Offer",
    assigned_agent_id: 1,
    message: "Ocean Estate on-site inspection completed. Preparing formal letter of intent.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 9,
    full_name: "Jean-Paul Sartre",
    email: "jp.sartre@lux-private.lu",
    phone: "+352 26 12 34 56",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Elysian Estate)",
    preferred_community: "Dubai Hills",
    property_id: 7,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 58000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 90,
    temperature: "HOT",
    stage: "Viewing",
    assigned_agent_id: 1,
    message: "Elysian Estate private viewing with financial director arranged.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 10,
    full_name: "Mona Al-Sabah",
    email: "mona@kuwait-diwan.kw",
    phone: "+965 9777 8899",
    lead_type: "Valuation Request",
    source_form: "Sell Property Valuation Form",
    preferred_community: "Palm Jumeirah",
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 65000000,
    cash_buyer: false,
    timeline: "Immediate / Ready",
    score: 75,
    temperature: "HOT",
    stage: "New",
    assigned_agent_id: 1,
    message: "Consignment of beachfront custom residence. Requesting off-market valuation.",
    last_activity_at: daysAgo(0) // New lead today!
  },

  // WARM Leads (Score 40 - 69)
  {
    id: 11,
    full_name: "Laurent Dupont",
    email: "laurent.dupont@geneve-wealth.ch",
    phone: "+41 22 700 8920",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Lumina Sky Tower)",
    preferred_community: "Business Bay",
    offplan_id: 1,
    budget_bracket_aed: "AED 3M - AED 10M",
    deal_value_aed: 7700000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "Interested in multiple units for portfolio allocation and Golden Visa.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 12,
    full_name: "Alexander Becker",
    email: "a.becker@munich-pe.de",
    phone: "+49 89 244 1109",
    lead_type: "Mortgage Inquiry",
    source_form: "Mortgage Advisor Request",
    preferred_community: "Dubai Marina",
    property_id: 10,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 14200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Modeling non-resident mortgage with 30% down payment.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 13,
    full_name: "Fahad Al-Husseini",
    email: "fahad@riyadh-ventures.sa",
    phone: "+966 50 123 9988",
    lead_type: "Valuation Request",
    source_form: "Sell Property Valuation Form",
    preferred_community: "Palm Jumeirah",
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 52000000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "New",
    assigned_agent_id: 1,
    message: "Owns custom beachfront villa on Frond E, requesting off-market valuation.",
    last_activity_at: daysAgo(0) // New today!
  },
  {
    id: 14,
    full_name: "Wei Zhang",
    email: "wei.zhang@singapore-capital.sg",
    phone: "+65 9123 4567",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Crest Beachfront)",
    preferred_community: "Jumeirah Coastline",
    offplan_id: 2,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 11800000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "Requesting high-res floor plans for Crest Beachfront 4-bedroom.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 15,
    full_name: "Oliver Sterling",
    email: "oliver@sterling-partners.co.uk",
    phone: "+44 20 7946 0912",
    lead_type: "Callback Request",
    source_form: "Floating Call Me Back",
    preferred_community: "Dubai Hills",
    property_id: 8,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 18500000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "New",
    assigned_agent_id: 2,
    message: "Please call back between 2pm-4pm Dubai time.",
    last_activity_at: daysAgo(0) // New today!
  },
  {
    id: 16,
    full_name: "Amara Ndiaye",
    email: "amara@dakar-global.com",
    phone: "+33 6 12 34 56 78",
    lead_type: "Register Interest",
    source_form: "VIP Concierge Modal",
    preferred_community: "Downtown",
    property_id: 5,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 6200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 55,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "Opera District luxury 2-bed requirement.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 17,
    full_name: "Marcus Lindqvist",
    email: "marcus@stockholm-nordic.se",
    phone: "+46 8 123 4567",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Bluewaters Haven)",
    preferred_community: "Dubai Marina",
    property_id: 11,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 8900000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Bluewaters apartment viewing with wife on Thursday.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 18,
    full_name: "Dr. Tariq Qureshi",
    email: "tariq.q@harleystreet.co.uk",
    phone: "+44 7700 900554",
    lead_type: "Mortgage Inquiry",
    source_form: "Mortgage Advisor Request",
    preferred_community: "Business Bay",
    property_id: 14,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 5200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 55,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Expatriate financing for duplex penthouse.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 19,
    full_name: "Beatriz Fernandez",
    email: "beatriz@madrid-capital.es",
    phone: "+34 600 123 456",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Solana Water Villas)",
    preferred_community: "Palm Jumeirah",
    offplan_id: 3,
    budget_bracket_aed: "AED 15M - AED 35M",
    deal_value_aed: 18200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "Overwater villa brochure requested.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 20,
    full_name: "Christian Wolff",
    email: "cwolff@frankfurt-invest.de",
    phone: "+49 69 900 1234",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Marina Gate Panoramic)",
    preferred_community: "Dubai Marina",
    property_id: 12,
    budget_bracket_aed: "AED 2M - AED 5M",
    deal_value_aed: 4750000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Marina Gate inspection scheduled.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 21,
    full_name: "Arthur Pendelton",
    email: "arthur@pendelton-holdings.co.uk",
    phone: "+44 131 496 0876",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Club Villas Sunset)",
    preferred_community: "Dubai Hills",
    property_id: 9,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 9800000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Golf view villa viewing.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 22,
    full_name: "Charlotte Dubois",
    email: "charlotte@paris-interiors.fr",
    phone: "+33 1 42 68 55 00",
    lead_type: "Register Interest",
    source_form: "VIP Concierge Modal",
    preferred_community: "Dubai Marina",
    property_id: 10,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 14200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Seeking furnished turn-key luxury apartment.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 23,
    full_name: "Matteo Rossi",
    email: "matteo@milano-design.it",
    phone: "+39 02 8899 1234",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Canal Promontory)",
    preferred_community: "Business Bay",
    property_id: 13,
    budget_bracket_aed: "AED 2M - AED 5M",
    deal_value_aed: 3400000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 55,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 3,
    message: "Canal view apartment walkthrough.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 24,
    full_name: "Amina Al-Nuaimi",
    email: "amina@abudhabi-capital.ae",
    phone: "+971 50 444 3322",
    lead_type: "Register Interest",
    source_form: "Home Hero Register",
    preferred_community: "Dubai Hills",
    property_id: 7,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 58000000,
    cash_buyer: true,
    timeline: "Immediate / Ready",
    score: 95,
    temperature: "HOT",
    stage: "Won",
    assigned_agent_id: 1,
    message: "Family villa inquiry successfully closed.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 25,
    full_name: "Gregory House",
    email: "ghouse@princeton-med.us",
    phone: "+1 609 555 0143",
    lead_type: "Mortgage Inquiry",
    source_form: "Mortgage Advisor Request",
    preferred_community: "Palm Jumeirah",
    property_id: 3,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 11500000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Golden visa eligibility through mortgage down payment.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 26,
    full_name: "Klaus Schmidt",
    email: "klaus@hamburg-shipping.de",
    phone: "+49 40 3344 5566",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Bluewaters)",
    preferred_community: "Dubai Marina",
    property_id: 11,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 8900000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Bluewaters live video tour.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 27,
    full_name: "Hans Zimmer",
    email: "hzimmer@vienna-sound.at",
    phone: "+43 1 515 2233",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (Palm Reserve Villa)",
    preferred_community: "Palm Jumeirah",
    property_id: 1,
    budget_bracket_aed: "AED 50M+",
    deal_value_aed: 48500000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 1,
    message: "Acoustic insulation specifics on Palm Villa.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 28,
    full_name: "Irina Sokolova",
    email: "irina@geneva-trust.ch",
    phone: "+41 22 819 0044",
    lead_type: "Viewing Request",
    source_form: "Book a Viewing (Grand Horizon)",
    preferred_community: "Downtown",
    property_id: 4,
    budget_bracket_aed: "AED 25M - AED 50M",
    deal_value_aed: 34000000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 65,
    temperature: "WARM",
    stage: "Viewing",
    assigned_agent_id: 2,
    message: "Private viewing for family principal.",
    last_activity_at: daysAgo(2)
  },
  {
    id: 29,
    full_name: "Fatima Al-Sayed",
    email: "fatima@manama-inv.bh",
    phone: "+973 3999 1234",
    lead_type: "Register Interest",
    source_form: "Home Hero Register",
    preferred_community: "Dubai Hills",
    property_id: 8,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 18500000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Modern villa preference near clubhouse.",
    last_activity_at: daysAgo(1)
  },
  {
    id: 30,
    full_name: "Edward Norton",
    email: "enorton@boston-biotech.us",
    phone: "+1 617 555 0177",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (Marina Promontory)",
    preferred_community: "Dubai Marina",
    property_id: 10,
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 14200000,
    cash_buyer: false,
    timeline: "Within 1-3 Months",
    score: 60,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 2,
    message: "Marina Promontory penthouse specs.",
    last_activity_at: daysAgo(2)
  },

  // STALE LEADS (No activity for 3+ days, for Stale Leads feature)
  {
    id: 31,
    full_name: "David K. Campbell",
    email: "dcampbell@toronto-realestate.ca",
    phone: "+1 416 555 0184",
    lead_type: "Property Inquiry",
    source_form: "Property Enquiry (JVC Townhouse)",
    preferred_community: "JVC",
    property_id: 15,
    budget_bracket_aed: "AED 2M - AED 5M",
    deal_value_aed: 2850000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 35,
    temperature: "COLD",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "Seeking 4-bedroom townhouse in JVC for rental yield.",
    last_activity_at: daysAgo(5) // Stale (5 days ago)
  },
  {
    id: 32,
    full_name: "Elena Petrova",
    email: "elena.p@cyprus-legal.cy",
    phone: "+357 25 123456",
    lead_type: "Valuation Request",
    source_form: "Sell Property Valuation Form",
    preferred_community: "Downtown",
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 12000000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 35,
    temperature: "COLD",
    stage: "New",
    assigned_agent_id: 1,
    message: "Selling 3-bedroom in Downtown with fountain view.",
    last_activity_at: daysAgo(4) // Stale (4 days ago)
  },
  {
    id: 33,
    full_name: "Kavita Singhania",
    email: "kavita@mumbai-tech.in",
    phone: "+91 98200 12345",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Zenith Duplexes)",
    preferred_community: "Downtown",
    offplan_id: 4,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 6400000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 35,
    temperature: "COLD",
    stage: "New",
    assigned_agent_id: 3,
    message: "Zenith Duplexes payment plan details.",
    last_activity_at: daysAgo(6) // Stale (6 days ago)
  },
  {
    id: 34,
    full_name: "Liam O'Connor",
    email: "liam@dublin-ventures.ie",
    phone: "+353 1 496 0123",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Vanguard Central)",
    preferred_community: "JVC",
    offplan_id: 6,
    budget_bracket_aed: "AED 1M - AED 3M",
    deal_value_aed: 1450000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 30,
    temperature: "COLD",
    stage: "Contacted",
    assigned_agent_id: 3,
    message: "JVC Vanguard Central pricing sheet.",
    last_activity_at: daysAgo(7) // Stale (7 days ago)
  },
  {
    id: 35,
    full_name: "Youssef El-Mansouri",
    email: "youssef@casablanca-fin.ma",
    phone: "+212 522 123456",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Aura Serenity)",
    preferred_community: "Dubai Hills",
    offplan_id: 5,
    budget_bracket_aed: "AED 25M - AED 50M",
    deal_value_aed: 24500000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 45,
    temperature: "WARM",
    stage: "New",
    assigned_agent_id: 3,
    message: "Aura Serenity master plan request.",
    last_activity_at: daysAgo(4) // Stale (4 days ago)
  },
  {
    id: 36,
    full_name: "Grace Hopper",
    email: "grace@tech-pioneers.com",
    phone: "+1 415 555 2671",
    lead_type: "Callback Request",
    source_form: "Floating Call Me Back",
    preferred_community: "Downtown",
    property_id: 6,
    budget_bracket_aed: "AED 3M - AED 10M",
    deal_value_aed: 4800000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 35,
    temperature: "COLD",
    stage: "New",
    assigned_agent_id: 2,
    message: "Old town courtyard residence callback.",
    last_activity_at: daysAgo(5) // Stale (5 days ago)
  },
  {
    id: 37,
    full_name: "Nasser Al-Falasi",
    email: "nasser@dubai-cre.ae",
    phone: "+971 55 889 0012",
    lead_type: "Valuation Request",
    source_form: "Sell Property Valuation Form",
    preferred_community: "Business Bay",
    budget_bracket_aed: "AED 10M - AED 25M",
    deal_value_aed: 16000000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 40,
    temperature: "WARM",
    stage: "Contacted",
    assigned_agent_id: 1,
    message: "Commercial and residential floors valuation.",
    last_activity_at: daysAgo(6) // Stale (6 days ago)
  },
  {
    id: 38,
    full_name: "Rohan Mehra",
    email: "rohan@delhi-exports.in",
    phone: "+91 98110 55443",
    lead_type: "Brochure Download",
    source_form: "Brochure Download (Lumina Sky Tower)",
    preferred_community: "Business Bay",
    offplan_id: 1,
    budget_bracket_aed: "AED 3M - AED 10M",
    deal_value_aed: 3850000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 30,
    temperature: "COLD",
    stage: "New",
    assigned_agent_id: 3,
    message: "Lumina payment plan request.",
    last_activity_at: daysAgo(8) // Stale (8 days ago)
  },
  {
    id: 39,
    full_name: "Benjamin Scott",
    email: "bscott@london-pe.co.uk",
    phone: "+44 20 7123 9988",
    lead_type: "Mortgage Inquiry",
    source_form: "Mortgage Advisor Request",
    preferred_community: "JVC",
    property_id: 16,
    budget_bracket_aed: "AED 2M - AED 5M",
    deal_value_aed: 2150000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 30,
    temperature: "COLD",
    stage: "Lost",
    assigned_agent_id: 3,
    message: "High ROI mortgage gearing calculation.",
    last_activity_at: daysAgo(10) // Lost
  },
  {
    id: 40,
    full_name: "Karim Benali",
    email: "karim@algiers-corp.dz",
    phone: "+213 21 44 55 66",
    lead_type: "Callback Request",
    source_form: "Floating Call Me Back",
    preferred_community: "Downtown",
    property_id: 5,
    budget_bracket_aed: "AED 5M - AED 15M",
    deal_value_aed: 6200000,
    cash_buyer: false,
    timeline: "3-6 Months",
    score: 35,
    temperature: "COLD",
    stage: "Lost",
    assigned_agent_id: 3,
    message: "Boulevard Opera unit callback.",
    last_activity_at: daysAgo(12) // Lost
  }
];

export const sampleViewings = [
  { id: 1, property_id: 1, lead_id: 1, agent_id: 2, viewing_date: "2026-10-06", viewing_time: "11:00 AM", viewing_mode: "VIP Chauffeur Accompanied", status: "Confirmed", notes: "Client arriving via private jet; Rolls-Royce transfer arranged from Al Maktoum Executive Terminal." },
  { id: 2, property_id: 4, lead_id: 3, agent_id: 2, viewing_date: "2026-10-07", viewing_time: "02:30 PM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Burj Khalifa penthouse inspection with legal counsel." },
  { id: 3, property_id: 10, lead_id: 17, agent_id: 2, viewing_date: "2026-10-08", viewing_time: "04:30 PM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Sunset viewing at Dubai Marina Promontory Suites." },
  { id: 4, property_id: 2, lead_id: 4, agent_id: 1, viewing_date: "2026-10-09", viewing_time: "10:30 AM", viewing_mode: "VIP Chauffeur Accompanied", status: "Confirmed", notes: "Ocean estate confidential walkthrough." },
  { id: 5, property_id: 7, lead_id: 2, agent_id: 1, viewing_date: "2026-10-10", viewing_time: "03:00 PM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Dubai Hills golf frontline mansion second viewing." },
  { id: 6, property_id: 11, lead_id: 26, agent_id: 2, viewing_date: "2026-10-11", viewing_time: "01:00 PM", viewing_mode: "Virtual Live Video Tour", status: "Confirmed", notes: "Live 4K video walkthrough with Hamburg buyer." },
  { id: 7, property_id: 8, lead_id: 15, agent_id: 2, viewing_date: "2026-10-12", viewing_time: "11:30 AM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Fairway Vistas family villa tour." },
  { id: 8, property_id: 12, lead_id: 20, agent_id: 2, viewing_date: "2026-10-13", viewing_time: "05:00 PM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Marina Gate sunset inspection." },
  { id: 9, property_id: 13, lead_id: 23, agent_id: 3, viewing_date: "2026-10-14", viewing_time: "10:00 AM", viewing_mode: "Private In-Person", status: "Confirmed", notes: "Marasi canal view apartment walkthrough." },
  { id: 10, property_id: 7, lead_id: 9, agent_id: 1, viewing_date: "2026-10-15", viewing_time: "02:00 PM", viewing_mode: "VIP Chauffeur Accompanied", status: "Confirmed", notes: "Private security protocol requested for viewing." }
];

export const sampleSales = [
  {
    id: 1,
    property_id: 1,
    property_title: "The Palm Signature Villa",
    community: "Palm Jumeirah",
    buyer_name: "Al-Nahyan Private Office",
    lead_id: 7,
    agent_id: 1,
    sale_price_aed: 46500000,
    commission_aed: 930000, // 2%
    dld_fee_paid_aed: 1860000, // 4%
    sale_date: "2026-09-22",
    transaction_reference: "DLD-TXN-2026-98101"
  },
  {
    id: 2,
    property_id: 4,
    property_title: "Downtown Royal Sky Penthouse",
    community: "Downtown",
    buyer_name: "Lord Harrington Capital",
    lead_id: 3,
    agent_id: 2,
    sale_price_aed: 32500000,
    commission_aed: 650000, // 2%
    dld_fee_paid_aed: 1300000,
    sale_date: "2026-09-15",
    transaction_reference: "DLD-TXN-2026-87422"
  },
  {
    id: 3,
    property_id: 7,
    property_title: "Dubai Hills Sanctuary Villa",
    community: "Dubai Hills",
    buyer_name: "Baroness Von Stauffenberg",
    lead_id: 5,
    agent_id: 1,
    sale_price_aed: 54000000,
    commission_aed: 1080000, // 2%
    dld_fee_paid_aed: 2160000,
    sale_date: "2026-09-02",
    transaction_reference: "DLD-TXN-2026-99310"
  },
  {
    id: 4,
    property_id: 10,
    property_title: "Marina Bluewaters Corner Suite",
    community: "Dubai Marina",
    buyer_name: "Geneva Maritime S.A.",
    lead_id: 12,
    agent_id: 2,
    sale_price_aed: 13800000,
    commission_aed: 276000, // 2%
    dld_fee_paid_aed: 552000,
    sale_date: "2026-08-19",
    transaction_reference: "DLD-TXN-2026-76190"
  },
  {
    id: 5,
    property_id: 14,
    property_title: "Business Bay Waterway Duplex",
    community: "Business Bay",
    buyer_name: "Dr. Cyrus Mistry",
    lead_id: 18,
    agent_id: 3,
    sale_price_aed: 4950000,
    commission_aed: 99000, // 2%
    dld_fee_paid_aed: 198000,
    sale_date: "2026-09-18",
    transaction_reference: "DLD-TXN-2026-99841"
  }
];

export const sampleNotes = [
  { id: 1, lead_id: 1, staff_id: 2, author_name: "Tariq Al-Hashimi", note_type: "Client Preference", note_text: "Prefers minimum 60ft private boat dock and high ceilings for contemporary art collection." },
  { id: 2, lead_id: 2, staff_id: 1, author_name: "Ayushi Kapoor", note_type: "Follow-up", note_text: "Proof of funds of AED 65M verified via Emirates NBD Private Banking letter." },
  { id: 3, lead_id: 3, staff_id: 2, author_name: "Tariq Al-Hashimi", note_type: "Client Preference", note_text: "Looking for tax residency and 10-year Golden Visa for family of 4 through off-plan portfolio." },
  { id: 4, lead_id: 4, staff_id: 1, author_name: "Ayushi Kapoor", note_type: "Viewing Feedback", note_text: "Loved the double-height ceiling in Downtown Duplex; requested structural floorplans for private elevator." },
  { id: 5, lead_id: 11, staff_id: 3, author_name: "Elena Rostova", note_type: "Internal Note", note_text: "Mortgage pre-approval in progress with Mashreq Al Islami for non-resident expatriate." }
];
